name: misxV2
description: misxV2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # =========================================================================
  # System                                                                  #
  # =========================================================================
  intl: ^0.17.0
  # reference - https://pub.dev/packages/intl
  # descryption - utility
  get: ^4.6.5
  # https://pub.dev/packages/get_storage
  # descryption - state manager
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/hive
  # descryption - local DB
  hive_generator: ^1.1.0
  # https://pub.dev/packages/hive_generator
  # descryption - local DB
  source_span: ^1.8.2
  # reference - https://pub.dev/packages/source_span
  # descryption - source formatting
  change_app_package_name: ^1.1.0
  # reference - https://pub.dev/packages/change_app_package_name
  # descryption - packagename change
  webview_flutter: ^3.0.4
  # reference - https://pub.dev/packages/webview_flutter
  # descryption - webview widget
  flutter_secure_storage: ^6.0.0
  # reference - https://pub.dev/packages/flutter_secure_storage
  # descryption - A Flutter plugin to store data in secure storage


  # =========================================================================
  # Network                                                                 #
  # =========================================================================
  http: ^0.13.5
  # reference - https://pub.dev/packages/http
  # descryption - making HTTP requests.
  json_serializable: ^6.4.0
  # reference - https://pub.dev/packages/json_serializable
  # descryption - builders for handling JSON
  dio: ^4.0.6
  # reference - https://pub.dev/packages/dio
  # descryption - Http client for Dart, which supports Interceptors, Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.


  # =========================================================================
  # ui                                                                      #
  # =========================================================================
  cupertino_icons: ^1.0.2
  # reference - https://pub.dev/packages/cupertino_icons
  # descryption - iOS style icon
  google_fonts: ^3.0.1
  # reference - https://pub.dev/packages/google_fonts
  # descryption - font
  font_awesome_flutter: ^10.1.0
  # reference - https://pub.dev/packages/font_awesome_flutter
  # descryption - font
  fl_chart: ^0.55.1
  # reference - https://pub.dev/packages/fl_chart
  # descryption - chart util
  month_year_picker: ^0.2.0+2
  # reference - https://pub.dev/packages/month_year_picker
  # descryption - month picker
  curved_navigation_bar: ^1.0.3
  # reference - https://pub.dev/packages/curved_navigation_bar
  # descryption - navigation bar design
  dialogs: ^0.0.7
  # reference - https://pub.dev/packages/dialogs
  # descryption - dialog design
  carousel_slider: ^4.1.1
  # reference - https://pub.dev/packages/carousel_slide
  # descryption - admob auto slide


  # get_storage: ^2.0.3
  # https://pub.dev/packages/get
  # descryption - persistent storage for simple data
  # shared_preferences: ^2.0.15
  # https://pub.dev/packages/shared_preferences
  # descryption - persistent storage for simple data (NSUserDefaults on iOS and macOS, SharedPreferences on Android)
  # permission_handler: ^10.0.0
  # reference - https://pub.dev/packages/permission_handler
  # descryption - permission manage
  # geolocator: ^9.0.1
  # reference - https://pub.dev/packages/geolocator
  # descryption - gps location service
  # google_maps_flutter: ^2.1.12
  # reference - https://pub.dev/packages/google_maps_flutter
  # descryption - map service
  # logger: ^1.1.0
  # reference - https://pub.dev/packages/logger
  # descryption - log util

  # later setup firebase


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  # reference - https://pub.dev/packages/flutter_lints
  # descryption - lint setup (analysis_options.yaml)
  build_runner: ^2.2.1
  # reference - https://pub.dev/packages/build_runner
  # descryption - generating files using Dart code

flutter:

  uses-material-design: true

  assets:
    - lib/assets/translations/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/json_dummy/


