name: renew_misx
description: renewal_misx

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # reference - https://pub.dev/packages/cupertino_icons
  # descryption - iOS style icon
  google_fonts: ^3.0.1
  # reference - https://pub.dev/packages/google_fonts
  # descryption - font
  font_awesome_flutter: ^10.1.0
  # reference - https://pub.dev/packages/font_awesome_flutter
  # descryption - font
  intl: ^0.17.0
  # reference - https://pub.dev/packages/intl
  # descryption - utility
  get: ^4.6.5
  # https://pub.dev/packages/get_storage
  # descryption - state manager
  # get_storage: ^2.0.3
  # https://pub.dev/packages/get
  # descryption - persistent storage for simple data
  # shared_preferences: ^2.0.15
  # https://pub.dev/packages/shared_preferences
  # descryption - persistent storage for simple data (NSUserDefaults on iOS and macOS, SharedPreferences on Android)
  fl_chart: ^0.55.1
  # reference - https://pub.dev/packages/fl_chart
  # descryption - chart util
  source_span: ^1.8.2
  # reference - https://pub.dev/packages/source_span
  # descryption - source formatting
  month_year_picker: ^0.2.0+2
  # reference - https://pub.dev/packages/month_year_picker
  # descryption - month picker
  webview_flutter: ^3.0.4
  # reference - https://pub.dev/packages/webview_flutter
  # descryption - webview widget
  # http: ^0.13.5 ( getX include http )
  # reference - https://pub.dev/packages/http - api call
  # descryption - making HTTP requests.
  # permission_handler: ^10.0.0
  # reference - https://pub.dev/packages/permission_handler
  # descryption - permission manage
  # geolocator: ^9.0.1
  # reference - https://pub.dev/packages/geolocator
  # descryption - gps location service
  # google_maps_flutter: ^2.1.12
  # reference - https://pub.dev/packages/google_maps_flutter
  # descryption - map service
  # sqflite: ^2.0.3+1
  # reference - https://pub.dev/packages/sqflite
  # descryption - SQLite plugin for Flutter
  # json_serializable: ^6.3.1
  # reference - https://pub.dev/packages/json_serializable
  # descryption - builders for handling JSON
  # logger: ^1.1.0
  # reference - https://pub.dev/packages/logger
  # descryption - log util

  # later setup firebase


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  # reference - https://pub.dev/packages/flutter_lints
  # descryption - lint setup (analysis_options.yaml)

flutter:

  uses-material-design: true

  assets:
    - lib/assets/translations/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/json_dummy/


